### ISSUE TITLE
Why not render children?

### ISSUE THREAD

**Issue by briandipalma** [kunokdev/react-window-size-listener#4]
The render method returns null, why not `this.props.children`?

**Comment by kunokdev** [comment]
The reason why we don't render children is mostly because original library done it like so. This library is just rewrite with core functionality. 

What would you gain from wrapping other components with this one? Do you have specific reason for better modularity? If there is legit reason to do so, I will make change, or PR from your side would be welcome too.

**Comment by briandipalma** [comment]
It means you don't need a wrapping element when using this component.

**Comment by kunokdev** [comment]
Ok, that seems good enough. 
I will then add support for this as well as HOC support as soon as I catch some free time.

**Comment by kunokdev** [comment]
Just added support for this in version 1.2.1, you can now use it as such: 

```
<WindowSizeListener
  onResize={(windowSize) => console.log(windowSize)}
>
  <h1>Hello world!</h1>
</WindowSizeListener>
```

**Comment by briandipalma** [comment]
Excellent, thanks.
